theme = "tokyonight"

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection" ]
X = "extend_line_up"
G = "goto_file_end"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[editor]
line-number = "relative"
scrolloff = 5
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# [editor.whitespace]
# render = "all"
# or control each character

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

